'use strict';
const $=id=>document.getElementById(id), esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=(x,compact=false)=>x==null?'UNKNOWN':new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',notation:compact?'compact':'standard',maximumFractionDigits:Math.abs(Number(x))>=1?2:8}).format(Number(x));
const num=(x,d=2)=>x==null?'UNKNOWN':Number(x).toFixed(d), date=x=>x==null?'UNKNOWN':new Date(x*1000).toLocaleString();
let base='',key='',csrf='',state=null,timer=null,epoch=0,selected=null,requestIds=new Map();
const titles={overview:'Command center',scanner:'Live scanner',radar:'Launch radar',portfolio:'Paper portfolio',strategies:'Strategy lab',backtest:'Backtesting',health:'System health',settings:'Settings'};
function notice(s){$('notice').textContent=s}
function origin(raw){if(!/^https?:\/\//i.test(raw))raw='https://'+raw;const u=new URL(raw);if(u.username||u.password||u.search||u.hash||!['','/'].includes(u.pathname))throw Error('Use only the backend origin; no credentials, path or query.');if(u.protocol!=='https:'&&!(u.protocol==='http:'&&['localhost','127.0.0.1'].includes(u.hostname)))throw Error('HTTPS is required.');return u.origin}
async function api(path,body){if(!base)throw Error('Connect first');const headers={};if(key){headers['X-NOVA-Key']=key;headers.Authorization='Bearer '+key}if(body!==undefined){headers['Content-Type']='application/json';headers['X-Nova-CSRF']=csrf}const r=await fetch(base+path,{method:body===undefined?'GET':'POST',headers,credentials:'omit',cache:'no-store',signal:AbortSignal.timeout(15000),...(body===undefined?{}:{body:JSON.stringify(body)})});let data;try{data=await r.json()}catch{throw Error('Backend returned non-JSON response ('+r.status+')')}if(!r.ok)throw Error(typeof data.detail==='string'?data.detail:JSON.stringify(data.detail||data.error||r.status));return data}
function canControl(){return Boolean(state?.controls_available&&key)}
function reset(){epoch++;clearTimeout(timer);timer=null;base='';key='';csrf='';state=null;requestIds.clear();$('admin-key').value='';$('connection').hidden=false;$('disconnect').hidden=true;$('mode').textContent='DISCONNECTED';['kill','apply-mode','start','stop','bt-submit','watch-add','reconcile'].forEach(id=>$(id).disabled=true);['stats','tokens','positions','closed','health-data','events','launches','strategy-list','risk-form','chart'].forEach(id=>$(id).innerHTML='');$('token-detail').hidden=true;notice('Disconnected. Key cleared from this tab.')}
async function refresh(generation=epoch){const next=await api('/api/state');if(generation!==epoch)return;if(next.api_version!=='2')throw Error('Dashboard requires NOVA API v2. Upload the matching backend.');state=next;render()}
async function poll(generation){try{await refresh(generation)}catch(e){if(generation===epoch){notice(e.message+' — displayed observations may be stale.');$('mode').textContent='CONNECTION ERROR';['start','apply-mode'].forEach(x=>$(x).disabled=true)}}finally{if(generation===epoch&&base)timer=setTimeout(()=>poll(generation),window.NOVA_CONFIG.pollMs)}}
$('connection').onsubmit=async e=>{e.preventDefault();clearTimeout(timer);const generation=++epoch;$('connect').disabled=true;try{base=origin($('backend-url').value.trim());key=$('admin-key').value.trim();if(key&&key.length<32)throw Error('Use the strong key you configured on the server (32+ characters).');const session=await api('/api/session');csrf=session.csrf;await refresh(generation);try{localStorage.setItem('nova_backend_origin',base)}catch{}$('admin-key').value='';$('connection').hidden=true;$('disconnect').hidden=false;timer=setTimeout(()=>poll(generation),window.NOVA_CONFIG.pollMs);await loadStrategies()}catch(e){base='';key='';csrf='';notice(e.message)}finally{$('connect').disabled=false}};
$('disconnect').onclick=reset;
try{$('backend-url').value=localStorage.getItem('nova_backend_origin')||window.NOVA_CONFIG.backendUrl}catch{$('backend-url').value=window.NOVA_CONFIG.backendUrl}
$('origin').textContent='Allowed dashboard origin: '+location.origin;
document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>{document.querySelectorAll('.page,.nav').forEach(x=>x.classList.remove('active'));$(b.dataset.page).classList.add('active');b.classList.add('active');$('title').textContent=titles[b.dataset.page];if(b.dataset.page==='strategies'&&base)loadStrategies()});
async function action(button,path,body={}){button.disabled=true;try{await api(path,body);await refresh()}catch(e){notice(e.message)}finally{button.disabled=!canControl()}}
$('apply-mode').onclick=()=>action($('apply-mode'),'/api/mode/'+$('mode-select').value);
$('start').onclick=()=>action($('start'),'/api/control/start');$('stop').onclick=()=>action($('stop'),'/api/control/stop');
$('kill').onclick=()=>{if(state.kill&&!confirm('Release the kill switch? This does not start the engine.'))return;action($('kill'),'/api/kill',{active:!state.kill})};
$('watch-form').onsubmit=e=>{e.preventDefault();action($('watch-add'),'/api/watch',{mint:$('watch-mint').value.trim()})};
$('reconcile').onclick=async()=>{try{$('reconcile-result').textContent=JSON.stringify(await api('/api/reconciliation'),null,2)}catch(e){notice(e.message)}};
function render(){const a=state.account,h=state.health;const controls=canControl();['kill','apply-mode','start','stop','bt-submit','watch-add'].forEach(id=>$(id).disabled=!controls);$('reconcile').disabled=false;$('kill').textContent=state.kill?'Release kill switch':'Activate kill switch';$('mode').textContent=state.mode.toUpperCase()+' / LIVE LOCKED';$('mode-select').value=state.mode.toUpperCase();$('engine-state').textContent=(state.engine_enabled?'RUNNING':'STOPPED')+' · '+h.status+' · '+(h.recovery_ok?'ledger recovered':'recovery required');notice(state.kill?'KILL ACTIVE. Entries blocked; exits continue when execution conditions permit.':!controls?'Read-only scanner. Configure a server key to enable paper controls.':!h.fresh?'Market observations unavailable or stale. Entries blocked.':'Connected. Simulated execution only; strategy profitability is unvalidated.');$('execution-model').textContent=state.execution_model;
$('stats').innerHTML=[['Paper equity',money(a.equity),a.equity_stale?'STALE MARKS':'After modeled exit costs'],['Net PnL',money(a.pnl),'Includes open positions'],['Exposure',money(a.exposure),state.positions.length+' positions'],['Observed tokens',state.tokens.length,'Solana market coverage']].map(([t,v,n])=>`<div class="stat"><label>${esc(t)}</label><strong>${esc(v)}</strong><small>${esc(n)}</small></div>`).join('');
const pts=state.equity.map(x=>x.value).filter(Number.isFinite);if(pts.length>1){const lo=Math.min(...pts),span=Math.max(...pts)-lo||1;$('chart').innerHTML=`<polyline points="${pts.map((v,i)=>`${10+680*i/(pts.length-1)},${140-110*(v-lo)/span}`).join(' ')}"/>`;$('chart-note').textContent=pts.length+' recorded observations'}else{$('chart').innerHTML='';$('chart-note').textContent='Waiting for equity observations.'}
$('positions').innerHTML=state.positions.length?state.positions.map(p=>`<article><div class="position"><strong>${esc(p.symbol)}</strong><span class="badge">PAPER LONG · ${esc(p.strategy)}</span><button data-close="${esc(p.id)}" ${controls?'':'disabled'}>Close paper</button></div><div class="detail-grid">${[['Entry',money(p.entry)],['Mark',money(p.mark)],['Realized',money(p.realized_pnl)],['Stop net',num(p.stop_net_pct)+'%'],['TP net',p.tp_net_pct.map(x=>num(x)+'%').join(' / ')],['Quantity',num(p.quantity,6)]].map(([k,v])=>`<div><span>${k}</span><b>${esc(v)}</b></div>`).join('')}</div><p class="muted">${p.stale?'STALE · ':''}${date(p.mark_at)} · ${esc(p.accounting_origin)}</p><p class="muted">${esc(p.threshold_note)}</p></article>`).join(''):'<article class="empty">No open positions. NO TRADE is valid.</article>';
$('positions').querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>action(b,'/api/paper/close',{position_id:b.dataset.close}));
$('closed').innerHTML=state.closed.map(t=>`<div class="event">${esc(t.symbol)} · ${money(t.realized_pnl)} · ${esc(t.exit_reason)} · ${date(t.closed_at)}</div>`).join('')||'<p class="muted">No completed paper trades.</p>';
$('health-data').innerHTML=[['Infrastructure',{...h,live_signer:'NOT IMPLEMENTED'}],['Risk state',state.risk_periods]].map(([label,obj])=>`<article><h3>${label}</h3><pre>${esc(JSON.stringify(obj,null,2))}</pre></article>`).join('');
$('events').innerHTML=state.events.map(e=>`<div class="event"><b>${esc(e.kind)}</b> · ${date(e.created_at)}<br>${esc(JSON.stringify(e.data))}</div>`).join('')||'<p class="muted">No events.</p>';
$('launches').innerHTML=state.launches.map(e=>`<article><b>${esc(e.symbol||'Unknown')}</b><p>${esc(e.name)}</p><p class="mono">${esc(e.mint)}</p><small>${date(e.received_at)} · PumpPortal</small><p class="amber">Creation observed · execution not approved</p></article>`).join('')||'<article>No public launch events received yet.</article>';
if(!$('risk-form').children.length){$('risk-form').innerHTML=Object.entries(state.limits).map(([k,v])=>`<label>${esc(k.replaceAll('_',' '))}<input data-risk="${esc(k)}" type="number" step="any" value="${Number(v)}"></label>`).join('')+`<button id="risk-save" ${controls?'':'disabled'}>Save limits</button>`}else if($('risk-save'))$('risk-save').disabled=!controls;
$('updated').textContent='LAST MARKET UPDATE '+date(h.last_success);renderTokens()}
$('risk-form').onsubmit=e=>{e.preventDefault();const body={};$('risk-form').querySelectorAll('[data-risk]').forEach(x=>{body[x.dataset.risk]=Number(x.value)});action($('risk-save'),'/api/settings',body)};
['search','fresh-filter','sort'].forEach(id=>$(id).oninput=renderTokens);
function renderTokens(){if(!state)return;const q=$('search').value.toLowerCase(),field=$('sort').value;const tokens=state.tokens.filter(t=>(t.symbol+t.mint).toLowerCase().includes(q)&&($('fresh-filter').value!=='fresh'||!t.stale)).sort((a,b)=>(field==='score'?b.decision.market_score-a.decision.market_score:field==='age'?(b.first_seen??0)-(a.first_seen??0):(b.liquidity??0)-(a.liquidity??0)));$('tokens').innerHTML=tokens.map(t=>`<tr><td><b>${esc(t.symbol)}</b><small>${esc(t.source)} / ${esc(t.venue)}</small></td><td>${money(t.price)}</td><td>${money(t.market_cap,true)}</td><td>${money(t.liquidity,true)}</td><td>${money(t.volume5m,true)} / ${money(t.volume1h,true)}</td><td>${num(t.decision.market_score,1)}<small>Coverage ${num(t.decision.coverage*100,0)}%</small></td><td>${t.stale?'STALE':Math.max(0,Math.round(Date.now()/1000-t.received_at))+'s'}</td><td><button data-token="${esc(t.mint)}">Inspect</button></td></tr>`).join('')||'<tr><td colspan="8" class="empty">No matching observations.</td></tr>';$('tokens').querySelectorAll('[data-token]').forEach(b=>b.onclick=()=>{selected=b.dataset.token;renderDetail()});if(selected)renderDetail()}
function renderDetail(){const t=state.tokens.find(x=>x.mint===selected);if(!t)return;const el=$('token-detail');el.hidden=false;el.innerHTML=`<h2>${esc(t.symbol)}</h2><p class="mono">${esc(t.mint)}</p><p>First observed: ${date(t.first_seen)}<br>Pair created: ${date(t.pair_created_at)}</p><p class="muted">Token creation, true source latency, holders, smart money, developer trust and rug score: UNKNOWN.</p><pre>${esc(JSON.stringify({decision:t.decision,security:t.security,v7:t.v7_scores},null,2))}</pre><button id="paper-open" ${canControl()&&state.mode==='paper'&&!t.stale?'':'disabled'}>Evaluate manual paper entry</button>`;$('paper-open').onclick=async()=>{if(!confirm('Paper research only. Strategy and risk checks still apply; security coverage may be partial. Continue?'))return;const id=requestIds.get(t.mint)||crypto.randomUUID();requestIds.set(t.mint,id);const b=$('paper-open');b.disabled=true;try{await api('/api/paper/open',{mint:t.mint,request_id:id,acknowledgement:'RESEARCH_ONLY_UNKNOWN_SECURITY'});requestIds.delete(t.mint);await refresh();notice('Paper order recorded. See Positions.')}catch(e){notice(e.message+' · A retry will reuse the same request id.')}finally{b.disabled=false}}}
async function loadStrategies(){try{const data=await api('/api/strategies');$('strategy-list').innerHTML=data.v7.map(s=>`<article><h3>${esc(s.name)}</h3><p class="badge">${s.enabled?'ENABLED':'DISABLED'} · PAPER ONLY</p><pre>${esc(JSON.stringify(s,null,2))}</pre></article>`).join('')+`<article><h3>Research baselines</h3><pre>${esc(JSON.stringify(data.research,null,2))}</pre><p class="muted">Unavailable: ${esc(data.not_implemented.join(', '))}</p></article>`}catch(e){notice(e.message)}}
$('backtest-form').onsubmit=async e=>{e.preventDefault();const b=$('bt-submit');b.disabled=true;try{const file=$('csv').files[0];if(file.size>1000000)throw Error('CSV must be under 1 MB');const lines=(await file.text()).trim().replace(/^\uFEFF/,'').split(/\r?\n/),keys=lines.shift().split(',').map(x=>x.trim());const bars=lines.map(line=>{const vals=line.split(',');if(vals.length!==keys.length)throw Error('Invalid CSV columns');return Object.fromEntries(keys.map((k,i)=>{if(vals[i].trim()===''||!Number.isFinite(Number(vals[i])))throw Error('Numeric CSV values required');return [k,Number(vals[i])]}))});const result=await api('/api/backtest',{bars,strategy:$('bt-strategy').value,fee_bps:Number($('bt-fee').value),slippage_bps:Number($('bt-slip').value),walk_forward:$('bt-walk').checked});$('backtest-result').textContent=JSON.stringify({...result,equity:undefined,trades:result.trades.slice(-20)},null,2)}catch(e){notice(e.message)}finally{b.disabled=!canControl()}};
